version: 2.1
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run:
        command: "echo running build job....."
    - run: "uname -a"

orbs:
  slack: circleci/slack@3.4.2
  cli: circleci/aws-cli@1.1.0
workflows:
  version: 2.1
  info-test:
    jobs:
      - build
