version: 2.1
executors:
  j7xtest:
    docker:
      - image: circleci/ruby:2.4.0
jobs:
  orbs:
    slack: circleci/slack@0.1.0
    cli: circleci/aws-cli@0.1.13
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    steps:
    - checkout
  test:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
    - TERM: dumb
    steps:
    - checkout
    - run:
        command: "echo file ${AUTO_FILE} dir ${AUTO_DIR}"
    - command: "uname -a"
workflows:
  version: 2
  workflow:
    jobs:
    - build
    - test
